# fly.toml app configuration file generated for openstatus-rumserver on 2024-04-04T10:36:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openstatus-rumserver'
primary_region = 'ams'

[build]
  dockerfile = './Dockerfile'

[deploy]
  strategy = 'canary'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 1000
    soft_limit = 500

[[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
