# fly.toml app configuration file generated for openstatus-api on 2023-09-13T17:29:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "openstatus-api"
primary_region = "ams"


[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
