blank_issues_enabled: false
contact_links:
  - name: Discord community support
    url: https://www.openstatus.dev/discord
    about: Need any help? Found any bug? Please chat with us via Discord.
