# https://github.com/kentcdodds/kentcdodds.com/blob/main/.github/workflows/deployment.yml
name: Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  tests:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      sqld:
        image: ghcr.io/tursodatabase/libsql-server:latest
        ports:
          - 8080:8080
        env:
          DATABASE_AUTH_TOKEN: "hello"

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      DATABASE_URL: http://127.0.0.1:8080
      DATABASE_AUTH_TOKEN: "hello"
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: 🔥 Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Download deps
        run: pnpm install

      - name: 🗃️ Run migrations
        run: pnpm migrate
        working-directory: ./packages/db

      - name: 💽  Seed database
        run: pnpm seed
        working-directory: ./packages/db

      - name: 🧪 Tests
        run: pnpm test
